# Tratamento SAEB

In [1]:
import pandas as pd

## SAEB 2017

In [3]:
caminho_do_arquivo = 'TS_ALUNO_9EF2017.csv'

lista_de_chunks = []

iterador_csv = pd.read_csv(caminho_do_arquivo, chunksize=100000)

print("Iniciando a leitura do arquivo em pedaços...")

for chunk in iterador_csv:
    lista_de_chunks.append(chunk)

print("\nJuntando todos os pedaços em um DataFrame final...")
df2017 = pd.concat(lista_de_chunks)

del lista_de_chunks

print("\nArquivo carregado com sucesso!")
print(f"--- O DataFrame final tem {df2017.shape[0]} linhas e {df2017.shape[1]} colunas. ---")


display(df2017.head())

Iniciando a leitura do arquivo em pedaços...

Juntando todos os pedaços em um DataFrame final...

Arquivo carregado com sucesso!
--- O DataFrame final tem 2341459 linhas e 92 colunas. ---

,ID_PROVA_BRASIL,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q048,TX_RESP_Q049,TX_RESP_Q050,TX_RESP_Q051,TX_RESP_Q052,TX_RESP_Q053,TX_RESP_Q054,TX_RESP_Q055,TX_RESP_Q056,TX_RESP_Q057
0,2017,1,11,6305476,1,61226262,1,1,745685,9,...,B,A,A,A,A,A,A,A,B,C
1,2017,1,11,6305476,1,61226262,1,1,930552,9,...,B,A,A,D,D,A,A,A,C,A
2,2017,1,11,6305476,1,61226262,1,1,745685,9,...,B,A,A,A,A,B,A,A,A,C
3,2017,1,11,6305476,1,61226262,1,1,826288,9,...,A,A,A,A,A,B,B,A,C,C
4,2017,1,11,6305476,1,61226262,1,1,772644,9,...,A,A,B,A,A,A,A,A,C,C

In [4]:
condicao1 = df2017['IN_PROFICIENCIA'] == 1
condicao2 = df2017['IN_PUBLICA'] == 1
condicao3 = df2017['IN_PREENCHIMENTO_QUESTIONARIO'] == 1
df2017_1 = df2017[condicao1 & condicao2 & condicao3].copy()

print(f"\n--- O DataFrame tem {df2017_1.shape[0]} linhas e {df2017_1.shape[1]} colunas. ---")

--- O DataFrame tem 1775388 linhas e 92 colunas. ---

In [5]:

colunas_para_manter_2017 = [

    'ID_PROVA_BRASIL','ID_REGIAO','ID_UF','ID_MUNICIPIO','ID_AREA','ID_LOCALIZACAO',
    'PROFICIENCIA_MT_SAEB','TX_RESP_Q002','TX_RESP_Q019', 'TX_RESP_Q023','TX_RESP_Q047', 'TX_RESP_Q048', 'TX_RESP_Q049',
    'TX_RESP_Q026','TX_RESP_Q027', 'TX_RESP_Q028', 'TX_RESP_Q030', 'TX_RESP_Q031','TX_RESP_Q046',
    'TX_RESP_Q005','TX_RESP_Q008',
    'TX_RESP_Q012','TX_RESP_Q013','TX_RESP_Q014','TX_RESP_Q015','TX_RESP_Q018','TX_RESP_Q022','TX_RESP_Q043','TX_RESP_Q044',
    'TX_RESP_Q045'

]

try:
    print("Selecionando as colunas especificadas...")
    df2017_2 = df2017_1[colunas_para_manter_2017].copy()
    print("Colunas selecionadas com sucesso!")

except KeyError as e:
    print(f"ERRO: Uma das colunas não foi encontrada no DataFrame. Verifique o nome: {e}")

mapa_renomeacao_2017 = {
    # Renomeações anteriores

    'ID_PROVA_BRASIL': 'ANO_SAEB',
    'TX_RESP_Q002': 'Q_COR_RACA',
    #A BRANCA - B PRETA - C PARDA - D AMARELO - E INDIGENA - F NAO QUERO DECLARAR

    'TX_RESP_Q019': 'Q_ESCOLARIDADE_MAE',
    'TX_RESP_Q023': 'Q_ESCOLARIDADE_PAI',
    #A Nunca estudou.	B Não completou a 4.ª série/5.º ano.	C Completou a 4.ª série/5.º ano, mas não completou a 8.ª série/9.º ano.	D Completou a 8.ª série/9.º ano, mas não completou o Ensino Médio.	E Completou o Ensino Médio, mas não completou a Faculdade.	F Completou a Faculdade.	G Não sei.

    'TX_RESP_Q047': 'Q_TIPO_ESCOLA_ANTERIOR',
    #A Somente em escola pública.	B Somente em escola particular.	C Em escola pública e em escola particular.

    'TX_RESP_Q048': 'Q_REPROVACAO',
    'TX_RESP_Q049': 'Q_ABANDONO',
    #A nao - #B uma vez - C# duas ou mais

    'TX_RESP_Q026': 'Q_PAIS_VAO_REUNIAO',
    #A Sempre ou quase sempre.	B De vez em quando.	C Nunca ou quase nunca.

    # NOVAS renomeações: Incentivo dos Pais
    'TX_RESP_Q027': 'Q_PAIS_INCENTIVA_ESTUDAR',
    'TX_RESP_Q028': 'Q_PAIS_INCENTIVA_DEVER',
    'TX_RESP_Q030': 'Q_PAIS_INCENTIVA_IR_ESCOLA',
    'TX_RESP_Q031': 'Q_PAIS_CONVERSA_SOBRE_ESCOLA',
    #A sim - #B não

    'TX_RESP_Q046': 'Q_IDADE_ENTRADA_NA_ESCOLA',
    #A Na creche (0 a 3 anos).	B Na pré-escola (4 a 5 anos).	C Na primeira série ou primeiro ano (6 a 7 anos).	D Depois da primeira série.

    'TX_RESP_Q018': 'Q_MORA_COM_MAE',
    'TX_RESP_Q022': 'Q_MORA_COM_PAI',
    #A sim - #B não

    # NOVAS renomeações: Bens Domésticos
    'TX_RESP_Q005': 'Q_BENS_TV_CORES',
    'TX_RESP_Q008': 'Q_BENS_GELADEIRA',
    'TX_RESP_Q012': 'Q_BENS_CARRO',
    'TX_RESP_Q013': 'Q_BENS_COMPUTADOR',
    'TX_RESP_Q014': 'Q_BENS_BANHEIRO',
    'TX_RESP_Q015': 'Q_BENS_QUARTOS',
    #A NÃO - B UMA - C DUAS - D TRES - E QUATRO OU MAIS

    'TX_RESP_Q043':'Q_LAZER',
    'TX_RESP_Q044':'Q_TRABALHO_DOMESTICO',
    #A Menos de 1 hora.	B Entre 1 e 2 horas.	C Mais de 2 horas, até 3 horas.	D Mais de 3 horas.	E Nada

    'TX_RESP_Q045':'Q_TRABALHO_FORA_DE_CASA'
    #A SIM - B NÃO
}


print("\nRenomeando colunas do questionário...")
df2017_3 = df2017_2.rename(columns=mapa_renomeacao_2017)
print("Colunas renomeadas!")


print("\n--- DataFrame de 2017 TRATADO E PRONTO PARA ANÁLISE ---")
print(f"O DataFrame tratado tem {df2017_3.shape[0]} linhas e {df2017_3.shape[1]} colunas.")

display(df2017_3.head())

Selecionando as colunas especificadas...
Colunas selecionadas com sucesso!

Renomeando colunas do questionário...
Colunas renomeadas!

--- DataFrame de 2017 TRATADO E PRONTO PARA ANÁLISE ---
O DataFrame tratado tem 1775388 linhas e 30 colunas.

,ANO_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_LOCALIZACAO,PROFICIENCIA_MT_SAEB,Q_COR_RACA,Q_ESCOLARIDADE_MAE,Q_ESCOLARIDADE_PAI,...,Q_BENS_GELADEIRA,Q_BENS_CARRO,Q_BENS_COMPUTADOR,Q_BENS_BANHEIRO,Q_BENS_QUARTOS,Q_MORA_COM_MAE,Q_MORA_COM_PAI,Q_LAZER,Q_TRABALHO_DOMESTICO,Q_TRABALHO_FORA_DE_CASA
0,2017,1,11,6305476,1,1,243.548333,B,F,F,...,B,C,B,D,D,A,A,C,E,B
1,2017,1,11,6305476,1,1,237.843906,C,C,D,...,C,B,C,C,D,A,A,D,A,B
2,2017,1,11,6305476,1,1,173.945673,B,B,D,...,C,C,B,E,E,A,A,D,B,NaN
3,2017,1,11,6305476,1,1,327.168454,C,D,E,...,B,B,E,C,D,A,A,D,A,B
4,2017,1,11,6305476,1,1,255.387166,C,E,E,...,B,A,C,B,D,A,C,D,B,B

In [6]:
# --- HARMONIZAÇÃO E SOBRESCRITA DAS RESPOSTAS DE 2017 ---

# 1. Escolaridade
mapa_esc_2017 = {'A': 'A', 'B': 'A', 'C': 'A', 'D': 'B', 'E': 'C', 'F': 'D', 'G': 'E'}
# Sobrescreve as colunas originais com os novos valores
df2017_3['Q_ESCOLARIDADE_MAE'] = df2017_3['Q_ESCOLARIDADE_MAE'].map(mapa_esc_2017)
df2017_3['Q_ESCOLARIDADE_PAI'] = df2017_3['Q_ESCOLARIDADE_PAI'].map(mapa_esc_2017)

# 2. Mora com os pais
mapa_mora_com = {'A': 'B', 'B': 'A', 'C': 'B'}
# Sobrescreve as colunas originais
df2017_3['Q_MORA_COM_MAE'] = df2017_3['Q_MORA_COM_MAE'].map(mapa_mora_com)
df2017_3['Q_MORA_COM_PAI'] = df2017_3['Q_MORA_COM_PAI'].map(mapa_mora_com)

# 3. Bens domésticos
mapa_itens = {'A':'A', 'B':'B', 'C':'C', 'D':'D', 'E':'D'}
colunas_bens = [
    'Q_BENS_TV_CORES', 'Q_BENS_GELADEIRA', 'Q_BENS_CARRO',
    'Q_BENS_COMPUTADOR', 'Q_BENS_BANHEIRO', 'Q_BENS_QUARTOS'
    # Adicione as outras colunas de bens se desejar
]
for coluna in colunas_bens:
    # Sobrescreve a coluna original dentro do loop
    df2017_3[coluna] = df2017_3[coluna].map(mapa_itens)

# 4. Tempo de lazer e trabalho doméstico
mapa_tempo = {'E':'A', 'A':'B', 'B':'C', 'C':'D', 'D':'D'}
# Sobrescreve as colunas originais
df2017_3['Q_LAZER'] = df2017_3['Q_LAZER'].map(mapa_tempo)
df2017_3['Q_TRABALHO_DOMESTICO'] = df2017_3['Q_TRABALHO_DOMESTICO'].map(mapa_tempo)

print("Todas as colunas foram transformadas e sobrescritas com sucesso!")

Todas as colunas foram transformadas e sobrescritas com sucesso!

In [7]:
import pandas as pd
import numpy as np

# --- PASSO 1: PADRONIZAR VALORES FALTANTES ---
valores_para_substituir = ['.', '*', np.nan]
print("Padronizando valores faltantes para '*' em todos os DataFrames...")
df2017_3 = df2017_3.replace(valores_para_substituir, '*')

nome_arquivo_final = 'SAEB_UNIFICADO_2017.csv'
print(f"\nExportando para '{nome_arquivo_final}'...")
df2017_3.to_csv(nome_arquivo_final, index=False, sep=';', encoding='utf-8-sig')
print("🎉 Processo concluído com sucesso!")

Padronizando valores faltantes para '*' em todos os DataFrames...

Exportando para 'SAEB_UNIFICADO_2017.csv'...
🎉 Processo concluído com sucesso!

## SAEB 2019

In [2]:
caminho_do_arquivo = 'TS_ALUNO_9EF2019.csv'

lista_de_chunks = []

iterador_csv = pd.read_csv(caminho_do_arquivo, sep=';', chunksize=100000)

print("Iniciando a leitura do arquivo em pedaços...")


for chunk in iterador_csv:
    lista_de_chunks.append(chunk)

print("\n\nJuntando todos os pedaços em um DataFrame final...")
df2019 = pd.concat(lista_de_chunks)

del lista_de_chunks

print("\nArquivo carregado com sucesso!")
print(f"--- O DataFrame final tem {df2019.shape[0]} linhas e {df2019.shape[1]} colunas. ---")


display(df2019.head())

Iniciando a leitura do arquivo em pedaços...

/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-1147874041.py:10: DtypeWarning: Columns (47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:

Juntando todos os pedaços em um DataFrame final...

Arquivo carregado com sucesso!
--- O DataFrame final tem 2388931 linhas e 129 colunas. ---

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q016,TX_RESP_Q017A,TX_RESP_Q017B,TX_RESP_Q017C,TX_RESP_Q017D,TX_RESP_Q017E,TX_RESP_Q018A,TX_RESP_Q018B,TX_RESP_Q018C,TX_RESP_Q019
0,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,A,D,A,D,B,A,C,B,A,C
1,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,A,D,A,D,B,A,A,A,A,C
2,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,A,D,A,D,C,A,C,B,B,D
3,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,A,C,A,D,C,A,A,A,A,D
4,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,A,C,A,*,B,A,B,A,A,C

In [3]:
condicao1 = df2019['IN_PROFICIENCIA_MT'] == 1
condicao2 = df2019['IN_PUBLICA'] == 1
condicao3 = df2019['IN_PREENCHIMENTO_QUESTIONARIO'] == 1
df2019_1 = df2019[condicao1 & condicao2 & condicao3].copy()

print(f"\n--- O DataFrame tem {df2019_1.shape[0]} linhas e {df2019_1.shape[1]} colunas. ---")

--- O DataFrame tem 1894919 linhas e 129 colunas. ---

In [4]:

colunas_para_manter_2019 = [

    'ID_SAEB','ID_REGIAO','ID_UF','ID_MUNICIPIO','ID_AREA','ID_LOCALIZACAO','TX_RESP_Q017E',
    'PROFICIENCIA_MT_SAEB','TX_RESP_Q002','TX_RESP_Q004', 'TX_RESP_Q005','TX_RESP_Q014', 'TX_RESP_Q015', 'TX_RESP_Q016',
    'TX_RESP_Q006E','TX_RESP_Q006A','TX_RESP_Q006B','TX_RESP_Q006C','TX_RESP_Q006D',
    'TX_RESP_Q013','TX_RESP_Q003A','TX_RESP_Q003B','TX_RESP_Q009E','TX_RESP_Q009A','TX_RESP_Q009G','TX_RESP_Q009F',
    'TX_RESP_Q009C','TX_RESP_Q009D', 'TX_RESP_Q017A','TX_RESP_Q017C'

]

try:
    print("Selecionando as colunas especificadas...")
    df2019_2 = df2019_1[colunas_para_manter_2019].copy()
    print("Colunas selecionadas com sucesso!")

except KeyError as e:
    print(f"ERRO: Uma das colunas não foi encontrada no DataFrame. Verifique o nome: {e}")

mapa_renomeacao_2019 = {
    # Renomeações anteriores

    'ID_SAEB': 'ANO_SAEB',
    'TX_RESP_Q002': 'Q_COR_RACA',
    #A BRANCA - B PRETA - C PARDA - D AMARELO - E INDIGENA - F NAO QUERO DECLARAR

    'TX_RESP_Q004': 'Q_ESCOLARIDADE_MAE',
    'TX_RESP_Q005': 'Q_ESCOLARIDADE_PAI',
    #ANão completou o 5º ano do Ensino Fundamental.
    #BEnsino Fundamental, até o 5º ano.
    #CEnsino Fundamental completo.
    #DEnsino Médio completo.
    #EEnsino Superior completo (faculdade ou graduação).
    #FNão sei.

    'TX_RESP_Q014': 'Q_TIPO_ESCOLA_ANTERIOR',
    #A Somente em escola pública.	B Somente em escola particular.	C Em escola pública e em escola particular.

    'TX_RESP_Q015': 'Q_REPROVACAO',
    'TX_RESP_Q016': 'Q_ABANDONO',
    #A nao - #B uma vez - C# duas ou mais

    'TX_RESP_Q006E': 'Q_PAIS_VAO_REUNIAO',
    #a	Nunca ou quase nunca.
    #b	De vez em quando.
    #c	Sempre ou quase sempre.

    # NOVAS renomeações: Incentivo dos Pais
    'TX_RESP_Q006B': 'Q_PAIS_INCENTIVA_ESTUDAR',
    'TX_RESP_Q006C': 'Q_PAIS_INCENTIVA_DEVER',
    'TX_RESP_Q006D': 'Q_PAIS_INCENTIVA_IR_ESCOLA',
    'TX_RESP_Q006A': 'Q_PAIS_CONVERSA_SOBRE_ESCOLA',
    #A sim - #B não

    'TX_RESP_Q013': 'Q_IDADE_ENTRADA_NA_ESCOLA',
    #A Na creche (0 a 3 anos).	B Na pré-escola (4 a 5 anos).	C Na primeira série ou primeiro ano (6 a 7 anos).	D Depois da primeira série.

    'TX_RESP_Q003A': 'Q_MORA_COM_MAE',
    'TX_RESP_Q003B': 'Q_MORA_COM_PAI',
    #A nao - #B sim

    # NOVAS renomeações: Bens Domésticos
    'TX_RESP_Q009E': 'Q_BENS_TV_CORES',
    'TX_RESP_Q009A': 'Q_BENS_GELADEIRA',
    'TX_RESP_Q009G': 'Q_BENS_CARRO',
    'TX_RESP_Q009C': 'Q_BENS_COMPUTADOR',
    'TX_RESP_Q009F': 'Q_BENS_BANHEIRO',
    'TX_RESP_Q009D': 'Q_BENS_QUARTOS',
    #A NÃO - B UMA - C DUAS - D TRES - E QUATRO OU MAIS

    'TX_RESP_Q017A':'Q_LAZER',
    'TX_RESP_Q017C':'Q_TRABALHO_DOMESTICO',
    #A Menos de 1 hora.	B Entre 1 e 2 horas.	C Mais de 2 horas, até 3 horas.	D Mais de 3 horas.	E Nada

    'TX_RESP_Q017E':'Q_TRABALHO_FORA_DE_CASA'
    #A SIM - B NÃO
}


print("\nRenomeando colunas do questionário...")
df2019_3 = df2019_2.rename(columns=mapa_renomeacao_2019)
print("Colunas renomeadas!")


print("\n--- DataFrame de 2019 TRATADO E PRONTO PARA ANÁLISE ---")
print(f"O DataFrame tratado tem {df2019_3.shape[0]} linhas e {df2019_3.shape[1]} colunas.")

display(df2019_3.head())

Selecionando as colunas especificadas...
Colunas selecionadas com sucesso!

Renomeando colunas do questionário...
Colunas renomeadas!

--- DataFrame de 2019 TRATADO E PRONTO PARA ANÁLISE ---
O DataFrame tratado tem 1894919 linhas e 30 colunas.

,ANO_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_LOCALIZACAO,Q_TRABALHO_FORA_DE_CASA,PROFICIENCIA_MT_SAEB,Q_COR_RACA,Q_ESCOLARIDADE_MAE,...,Q_MORA_COM_MAE,Q_MORA_COM_PAI,Q_BENS_TV_CORES,Q_BENS_GELADEIRA,Q_BENS_CARRO,Q_BENS_BANHEIRO,Q_BENS_COMPUTADOR,Q_BENS_QUARTOS,Q_LAZER,Q_TRABALHO_DOMESTICO
0,2019,1,11,6311030,2,1,A,239.920418,A,A,...,B,B,B,B,B,B,*,D,D,D
1,2019,1,11,6311030,2,1,A,244.042645,C,E,...,B,A,B,B,B,B,A,D,D,D
2,2019,1,11,6311030,2,1,A,230.205828,C,F,...,B,.,B,B,A,B,A,C,D,D
3,2019,1,11,6311030,2,1,A,268.977498,C,E,...,B,B,C,B,B,B,B,D,C,D
4,2019,1,11,6311030,2,1,A,260.803189,A,B,...,B,B,B,B,B,C,A,D,C,*

In [5]:
# --- HARMONIZAÇÃO E SOBRESCRITA DAS RESPOSTAS DE 2019 ---

# 1. Escolaridade
# CORREÇÃO: As chaves do dicionário agora são minúsculas ('a', 'b', 'c'...)
mapa_esc_2019_em_diante = {
    'A': 'A', #'Fundamental Incompleto',
    'B': 'A', #'Fundamental Incompleto',
    'C': 'B', #'Fundamental Completo',
    'D': 'C', #'Médio Completo',
    'E': 'D', #'Superior Completo',
    'F': 'E'  #'Não sei'
}

# CORREÇÃO: Atribua o resultado de volta para sobrescrever as colunas
df2019_3['Q_ESCOLARIDADE_MAE'] = df2019_3['Q_ESCOLARIDADE_MAE'].map(mapa_esc_2019_em_diante)
df2019_3['Q_ESCOLARIDADE_PAI'] = df2019_3['Q_ESCOLARIDADE_PAI'].map(mapa_esc_2019_em_diante)


# 2. Frequência dos Pais na Reunião
# CORREÇÃO: As chaves do dicionário agora são minúsculas
mapa_reuniao_2019 = {
    'A': 'C', # Nunca ou quase nunca -> C
    'B': 'B', # De vez em quando -> B
    'C': 'A'  # Sempre ou quase sempre -> A
}

# CORREÇÃO: Atribua o resultado de volta para sobrescrever a coluna
df2019_3['Q_PAIS_VAO_REUNIAO'] = df2019_3['Q_PAIS_VAO_REUNIAO'].map(mapa_reuniao_2019)


# 3. Incentivo dos Pais
# CORREÇÃO: As chaves do dicionário agora são minúsculas
mapa_frequencia_para_binario = {
    'A': 'B', # Nunca -> Não
    'B': 'A', # De vez em quando -> Sim
    'C': 'A'  # Sempre -> Sim
}

colunas_para_unificar = [
    'Q_PAIS_INCENTIVA_ESTUDAR',
    'Q_PAIS_INCENTIVA_DEVER',
    'Q_PAIS_INCENTIVA_IR_ESCOLA',
    'Q_PAIS_CONVERSA_SOBRE_ESCOLA'
]

for coluna in colunas_para_unificar:
    # CORREÇÃO: Atribua o resultado de volta para sobrescrever a coluna
    df2019_3[coluna] = df2019_3[coluna].map(mapa_frequencia_para_binario)


mapa_trabalho_fora = {
    'A': 'B', # Nunca -> Não
    'B': 'A', # De vez em quando -> Sim
    'C': 'A',  # Sempre -> Sim
    'D': 'A'
}
df2019_3['Q_TRABALHO_FORA_DE_CASA'] = df2019_3['Q_TRABALHO_FORA_DE_CASA'].map(mapa_trabalho_fora)

print("Todas as colunas de 2019 foram transformadas e sobrescritas com sucesso!")

Todas as colunas de 2019 foram transformadas e sobrescritas com sucesso!

In [6]:
import pandas as pd
import numpy as np

# --- PASSO 1: PADRONIZAR VALORES FALTANTES ---
valores_para_substituir = ['.', '*', np.nan]
print("Padronizando valores faltantes para '*' em todos os DataFrames...")
df2019_3 = df2019_3.replace(valores_para_substituir, '*')

nome_arquivo_final = 'SAEB_UNIFICADO_2019.csv'
print(f"\nExportando para '{nome_arquivo_final}'...")
df2019_3.to_csv(nome_arquivo_final, index=False, sep=';', encoding='utf-8-sig')
print("🎉 Processo concluído com sucesso!")

Padronizando valores faltantes para '*' em todos os DataFrames...

Exportando para 'SAEB_UNIFICADO_2019.csv'...
🎉 Processo concluído com sucesso!

## SAEB 2021

In [3]:
caminho_do_arquivo = 'TS_ALUNO_9EF2021.csv'

lista_de_chunks = []

iterador_csv = pd.read_csv(caminho_do_arquivo, sep=';', chunksize=100000)

print("Iniciando a leitura do arquivo em pedaços...")


for chunk in iterador_csv:
    lista_de_chunks.append(chunk)

print("\n\nJuntando todos os pedaços em um DataFrame final...")
df2021 = pd.concat(lista_de_chunks)

del lista_de_chunks

print("\nArquivo carregado com sucesso!")
print(f"--- O DataFrame final tem {df2021.shape[0]} linhas e {df2021.shape[1]} colunas. ---")


display(df2021.head())

Iniciando a leitura do arquivo em pedaços...

/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-3518785831.py:10: DtypeWarning: Columns (42,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:

Juntando todos os pedaços em um DataFrame final...

Arquivo carregado com sucesso!
--- O DataFrame final tem 2591937 linhas e 144 colunas. ---

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q21,TX_RESP_Q22a,TX_RESP_Q22b,TX_RESP_Q22c,TX_RESP_Q22d,TX_RESP_Q22e,TX_RESP_Q22f,TX_RESP_Q22g,TX_RESP_Q22h,TX_RESP_Q22i
0,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,C,D,B,D,B,B,B,C,A
1,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,B,B,C,B,C,B,B,B,B,C
2,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,.,.,.,.,.,.,.,.,.,.
3,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,.,.,.,.,.,.,.,.,.,.
4,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,D,D,D,D,C,B,D,D,D

In [4]:
condicao1 = df2021['IN_PROFICIENCIA_MT'] == 1
condicao2 = df2021['IN_PUBLICA'] == 1
condicao3 = df2021['IN_PREENCHIMENTO_QUESTIONARIO'] == 1
df2021_1 = df2021[condicao1 & condicao2 & condicao3].copy()

print(f"\n--- O DataFrame tem {df2021_1.shape[0]} linhas e {df2021_1.shape[1]} colunas. ---")

--- O DataFrame tem 1877738 linhas e 144 colunas. ---

In [5]:

colunas_para_manter_2021 = [

    'ID_SAEB','ID_REGIAO','ID_UF','ID_MUNICIPIO','ID_AREA','ID_LOCALIZACAO','TX_RESP_Q20d',
    'PROFICIENCIA_MT_SAEB','TX_RESP_Q04','TX_RESP_Q07', 'TX_RESP_Q08','TX_RESP_Q17', 'TX_RESP_Q18', 'TX_RESP_Q19',
    'TX_RESP_Q09f','TX_RESP_Q09b','TX_RESP_Q09c','TX_RESP_Q09d','TX_RESP_Q09e','TX_RESP_Q16',
    'TX_RESP_Q06a','TX_RESP_Q06b',
    'TX_RESP_Q11e',
    'TX_RESP_Q11a',
    'TX_RESP_Q11g',
    'TX_RESP_Q11c',
    'TX_RESP_Q11f',
    'TX_RESP_Q11d',
    'TX_RESP_Q20c','TX_RESP_Q20e'

]

try:
    print("Selecionando as colunas especificadas...")
    df2021_2 = df2021_1[colunas_para_manter_2021].copy()
    print("Colunas selecionadas com sucesso!")

except KeyError as e:
    print(f"ERRO: Uma das colunas não foi encontrada no DataFrame. Verifique o nome: {e}")

mapa_renomeacao_2021 = {
    # Renomeações anteriores

    'ID_SAEB': 'ANO_SAEB',
    'TX_RESP_Q04': 'Q_COR_RACA',
    #A BRANCA - B PRETA - C PARDA - D AMARELO - E INDIGENA - F NAO QUERO DECLARAR

    'TX_RESP_Q07': 'Q_ESCOLARIDADE_MAE',
    'TX_RESP_Q08': 'Q_ESCOLARIDADE_PAI',
    #ANão completou o 5º ano do Ensino Fundamental.
    #BEnsino Fundamental, até o 5º ano.
    #CEnsino Fundamental completo.
    #DEnsino Médio completo.
    #EEnsino Superior completo (faculdade ou graduação).
    #FNão sei.

    'TX_RESP_Q17': 'Q_TIPO_ESCOLA_ANTERIOR',
    #A Somente em escola pública.	B Somente em escola particular.	C Em escola pública e em escola particular.

    'TX_RESP_Q18': 'Q_REPROVACAO',
    'TX_RESP_Q19': 'Q_ABANDONO',
    #A nao - #B uma vez - C# duas ou mais

    'TX_RESP_Q09f': 'Q_PAIS_VAO_REUNIAO',
    #a	Nunca ou quase nunca.
    #b	De vez em quando.
    #c	Sempre ou quase sempre.

    # NOVAS renomeações: Incentivo dos Pais
    'TX_RESP_Q09c': 'Q_PAIS_INCENTIVA_ESTUDAR',
    'TX_RESP_Q09d': 'Q_PAIS_INCENTIVA_DEVER',
    'TX_RESP_Q09e': 'Q_PAIS_INCENTIVA_IR_ESCOLA',
    'TX_RESP_Q09b': 'Q_PAIS_CONVERSA_SOBRE_ESCOLA',
    #A sim - #B não

    'TX_RESP_Q16': 'Q_IDADE_ENTRADA_NA_ESCOLA',
    #A Na creche (0 a 3 anos).	B Na pré-escola (4 a 5 anos).	C Na primeira série ou primeiro ano (6 a 7 anos).	D Depois da primeira série.

    'TX_RESP_Q06a': 'Q_MORA_COM_MAE',
    'TX_RESP_Q06b': 'Q_MORA_COM_PAI',
    #A nao - #B sim

    # NOVAS renomeações: Bens Domésticos
    'TX_RESP_Q11e': 'Q_BENS_TV_CORES',
    'TX_RESP_Q11a': 'Q_BENS_GELADEIRA',
    'TX_RESP_Q11g': 'Q_BENS_CARRO',
    'TX_RESP_Q11c': 'Q_BENS_COMPUTADOR',
    'TX_RESP_Q11f': 'Q_BENS_BANHEIRO',
    'TX_RESP_Q11d': 'Q_BENS_QUARTOS',
    #A NÃO - B UMA - C DUAS - D TRES - E QUATRO OU MAIS

    'TX_RESP_Q20e':'Q_LAZER',
    'TX_RESP_Q20c':'Q_TRABALHO_DOMESTICO',
    #A Menos de 1 hora.	B Entre 1 e 2 horas.	C Mais de 2 horas, até 3 horas.	D Mais de 3 horas.	E Nada
     'TX_RESP_Q20d':'Q_TRABALHO_FORA_DE_CASA',
}


print("\nRenomeando colunas do questionário...")
df2021_3 = df2021_2.rename(columns=mapa_renomeacao_2021)
print("Colunas renomeadas!")


print("\n--- DataFrame de 2021 TRATADO E PRONTO PARA ANÁLISE ---")
print(f"O DataFrame tratado tem {df2021_3.shape[0]} linhas e {df2021_3.shape[1]} colunas.")

display(df2021_3.head())

Selecionando as colunas especificadas...
Colunas selecionadas com sucesso!

Renomeando colunas do questionário...
Colunas renomeadas!

--- DataFrame de 2021 TRATADO E PRONTO PARA ANÁLISE ---
O DataFrame tratado tem 1877738 linhas e 30 colunas.

,ANO_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_LOCALIZACAO,Q_TRABALHO_FORA_DE_CASA,PROFICIENCIA_MT_SAEB,Q_COR_RACA,Q_ESCOLARIDADE_MAE,...,Q_MORA_COM_MAE,Q_MORA_COM_PAI,Q_BENS_TV_CORES,Q_BENS_GELADEIRA,Q_BENS_CARRO,Q_BENS_COMPUTADOR,Q_BENS_BANHEIRO,Q_BENS_QUARTOS,Q_TRABALHO_DOMESTICO,Q_LAZER
0,2021,1,11,6316600,2,1,D,234.739479,A,D,...,B,B,B,A,A,A,B,D,D,B
1,2021,1,11,6316600,2,1,D,165.188854,C,F,...,B,B,C,B,A,B,C,D,D,C
4,2021,1,11,6316600,2,1,A,208.589694,A,B,...,B,B,B,B,.,C,B,B,A,D
5,2021,1,11,6316600,2,1,B,188.686380,C,F,...,B,B,B,B,B,A,B,D,B,B
6,2021,1,11,6316600,2,1,D,283.393079,D,F,...,B,A,A,B,A,A,B,D,C,D

In [6]:
# --- HARMONIZAÇÃO E SOBRESCRITA DAS RESPOSTAS DE 2019 ---

# 1. Escolaridade
# CORREÇÃO: As chaves do dicionário agora são minúsculas ('a', 'b', 'c'...)
mapa_esc_2021_em_diante = {
    'A': 'A', #'Fundamental Incompleto',
    'B': 'A', #'Fundamental Incompleto',
    'C': 'B', #'Fundamental Completo',
    'D': 'C', #'Médio Completo',
    'E': 'D', #'Superior Completo',
    'F': 'E'  #'Não sei'
}

# CORREÇÃO: Atribua o resultado de volta para sobrescrever as colunas
df2021_3['Q_ESCOLARIDADE_MAE'] = df2021_3['Q_ESCOLARIDADE_MAE'].map(mapa_esc_2021_em_diante)
df2021_3['Q_ESCOLARIDADE_PAI'] = df2021_3['Q_ESCOLARIDADE_PAI'].map(mapa_esc_2021_em_diante)


# 2. Frequência dos Pais na Reunião
# CORREÇÃO: As chaves do dicionário agora são minúsculas
mapa_reuniao_2021 = {
    'A': 'C', # Nunca ou quase nunca -> C
    'B': 'B', # De vez em quando -> B
    'C': 'A'  # Sempre ou quase sempre -> A
}

# CORREÇÃO: Atribua o resultado de volta para sobrescrever a coluna
df2021_3['Q_PAIS_VAO_REUNIAO'] = df2021_3['Q_PAIS_VAO_REUNIAO'].map(mapa_reuniao_2021)


# 3. Incentivo dos Pais
# CORREÇÃO: As chaves do dicionário agora são minúsculas
mapa_frequencia_para_binario = {
    'A': 'B', # Nunca -> Não
    'B': 'A', # De vez em quando -> Sim
    'C': 'A'  # Sempre -> Sim
}

colunas_para_unificar = [
    'Q_PAIS_INCENTIVA_ESTUDAR',
    'Q_PAIS_INCENTIVA_DEVER',
    'Q_PAIS_INCENTIVA_IR_ESCOLA',
    'Q_PAIS_CONVERSA_SOBRE_ESCOLA'
]

for coluna in colunas_para_unificar:
    # CORREÇÃO: Atribua o resultado de volta para sobrescrever a coluna
    df2021_3[coluna] = df2021_3[coluna].map(mapa_frequencia_para_binario)

mapa_trabalho_fora = {
    'A': 'B', # Nunca -> Não
    'B': 'A', # De vez em quando -> Sim
    'C': 'A',  # Sempre -> Sim
    'D': 'A'
}
df2021_3['Q_TRABALHO_FORA_DE_CASA'] = df2021_3['Q_TRABALHO_FORA_DE_CASA'].map(mapa_trabalho_fora)

print("Todas as colunas de 2021 foram transformadas e sobrescritas com sucesso!")

Todas as colunas de 2021 foram transformadas e sobrescritas com sucesso!

In [7]:
import pandas as pd
import numpy as np

# --- PASSO 1: PADRONIZAR VALORES FALTANTES ---
valores_para_substituir = ['.', '*', np.nan]
print("Padronizando valores faltantes para '*' em todos os DataFrames...")
df2021_3 = df2021_3.replace(valores_para_substituir, '*')

nome_arquivo_final = 'SAEB_UNIFICADO_2021.csv'
print(f"\nExportando para '{nome_arquivo_final}'...")
df2021_3.to_csv(nome_arquivo_final, index=False, sep=';', encoding='utf-8-sig')
print("🎉 Processo concluído com sucesso!")

Padronizando valores faltantes para '*' em todos os DataFrames...

Exportando para 'SAEB_UNIFICADO_2021.csv'...
🎉 Processo concluído com sucesso!

## SAEB 2023

In [ ]:
caminho_do_arquivo = 'TS_ALUNO_9EF2023.csv'

lista_de_chunks = []

iterador_csv = pd.read_csv(caminho_do_arquivo, sep=';', chunksize=100000)

print("Iniciando a leitura do arquivo em pedaços...")


for chunk in iterador_csv:
    lista_de_chunks.append(chunk)

print("\n\nJuntando todos os pedaços em um DataFrame final...")
df2023 = pd.concat(lista_de_chunks)

del lista_de_chunks

print("\nArquivo carregado com sucesso!")
print(f"--- O DataFrame final tem {df2023.shape[0]} linhas e {df2023.shape[1]} colunas. ---")


display(df2023.head())

Iniciando a leitura do arquivo em pedaços...

/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:
/tmp/ipython-input-865511589.py:10: DtypeWarning: Columns (41,42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in iterador_csv:

Juntando todos os pedaços em um DataFrame final...

In [2]:
caminho_arquivo = 'TS_ALUNO_9EF2023.csv'

print("Iniciando a leitura e filtragem em chunks...")

lista_chunks_filtrados = []

iterador_csv = pd.read_csv(
    caminho_arquivo,
    sep=';',
    encoding='latin1',
    chunksize=100000,
    low_memory=False
)

# Itera sobre cada pedaço do arquivo
for i, chunk in enumerate(iterador_csv):
    print(f"Processando chunk {i+1}...", end='\r')

    # Aplica as mesmas 3 condições, mas apenas no chunk (que é pequeno)
    condicao1 = chunk['IN_PUBLICA'] == 1
    condicao2 = chunk['IN_PREENCHIMENTO_QUESTIONARIO'] == 1
    condicao3 = chunk['IN_PROFICIENCIA_MT'] == 1

    chunk_filtrado = chunk[condicao1 & condicao2 & condicao3]

    # Adiciona o chunk JÁ FILTRADO à nossa lista
    if not chunk_filtrado.empty:
        lista_chunks_filtrados.append(chunk_filtrado)

print("\n\nLeitura finalizada. Concatenando os chunks filtrados...")

# No final, junta apenas os pedaços filtrados, que são muito menores
df2023_1 = pd.concat(lista_chunks_filtrados, ignore_index=True).copy()

print(f"\n--- O DataFrame final tem {df2023_1.shape[0]} linhas e {df2023_1.shape[1]} colunas. ---")

Iniciando a leitura e filtragem em chunks...
Processando chunk 26...

Leitura finalizada. Concatenando os chunks filtrados...

--- O DataFrame final tem 2037884 linhas e 153 colunas. ---

In [3]:

colunas_para_manter_2023 = [

    'ID_SAEB','ID_REGIAO','ID_UF','ID_MUNICIPIO','ID_AREA','ID_LOCALIZACAO','TX_RESP_Q21d',
    'PROFICIENCIA_MT_SAEB','TX_RESP_Q04','TX_RESP_Q08', 'TX_RESP_Q09','TX_RESP_Q20', 'TX_RESP_Q18', 'TX_RESP_Q19',
    'TX_RESP_Q10f','TX_RESP_Q10b','TX_RESP_Q10c','TX_RESP_Q10d','TX_RESP_Q10e','TX_RESP_Q17',
    'TX_RESP_Q07a','TX_RESP_Q07b',
    'TX_RESP_Q12a',
    'TX_RESP_Q12b',
    'TX_RESP_Q12c',
    'TX_RESP_Q12d',
    'TX_RESP_Q12e',
    'TX_RESP_Q12f',
    'TX_RESP_Q21c','TX_RESP_Q21e'

]

try:
    print("Selecionando as colunas especificadas...")
    df2023_2 = df2023_1[colunas_para_manter_2023].copy()
    print("Colunas selecionadas com sucesso!")

except KeyError as e:
    print(f"ERRO: Uma das colunas não foi encontrada no DataFrame. Verifique o nome: {e}")

mapa_renomeacao_2023 = {
    # Renomeações anteriores

    'ID_SAEB': 'ANO_SAEB',
    'TX_RESP_Q04': 'Q_COR_RACA',
    #A BRANCA - B PRETA - C PARDA - D AMARELO - E INDIGENA - F NAO QUERO DECLARAR

    'TX_RESP_Q08': 'Q_ESCOLARIDADE_MAE',
    'TX_RESP_Q09': 'Q_ESCOLARIDADE_PAI',
    #ANão completou o 5º ano do Ensino Fundamental.
    #BEnsino Fundamental, até o 5º ano.
    #CEnsino Fundamental completo.
    #DEnsino Médio completo.
    #EEnsino Superior completo (faculdade ou graduação).
    #FNão sei.

    'TX_RESP_Q18': 'Q_TIPO_ESCOLA_ANTERIOR',
    #A Somente em escola pública.	B Somente em escola particular.	C Em escola pública e em escola particular.

    'TX_RESP_Q19': 'Q_REPROVACAO',
    'TX_RESP_Q20': 'Q_ABANDONO',
    #A nao - #B uma vez - C# duas ou mais

    'TX_RESP_Q10f': 'Q_PAIS_VAO_REUNIAO',
    #a	Nunca ou quase nunca.
    #b	De vez em quando.
    #c	Sempre ou quase sempre.

    # NOVAS renomeações: Incentivo dos Pais
    'TX_RESP_Q10c': 'Q_PAIS_INCENTIVA_ESTUDAR',
    'TX_RESP_Q10d': 'Q_PAIS_INCENTIVA_DEVER',
    'TX_RESP_Q10e': 'Q_PAIS_INCENTIVA_IR_ESCOLA',
    'TX_RESP_Q10b': 'Q_PAIS_CONVERSA_SOBRE_ESCOLA',
    #A sim - #B não

    'TX_RESP_Q17': 'Q_IDADE_ENTRADA_NA_ESCOLA',
    #A Na creche (0 a 3 anos).	B Na pré-escola (4 a 5 anos).	C Na primeira série ou primeiro ano (6 a 7 anos).	D Depois da primeira série.

    'TX_RESP_Q07a': 'Q_MORA_COM_MAE',
    'TX_RESP_Q07b': 'Q_MORA_COM_PAI',
    #A nao - #B sim

    # NOVAS renomeações: Bens Domésticos
    'TX_RESP_Q12d': 'Q_BENS_TV_CORES',
    'TX_RESP_Q12a': 'Q_BENS_GELADEIRA',
    'TX_RESP_Q12f': 'Q_BENS_CARRO',
    'TX_RESP_Q12b': 'Q_BENS_COMPUTADOR',
    'TX_RESP_Q12e': 'Q_BENS_BANHEIRO',
    'TX_RESP_Q12c': 'Q_BENS_QUARTOS',
    #A NÃO - B UMA - C DUAS - D TRES - E QUATRO OU MAIS

    'TX_RESP_Q21e':'Q_LAZER',
    'TX_RESP_Q21c':'Q_TRABALHO_DOMESTICO',
    #A Menos de 1 hora.	B Entre 1 e 2 horas.	C Mais de 2 horas, até 3 horas.	D Mais de 3 horas.	E Nada

    'TX_RESP_Q21d':'Q_TRABALHO_FORA_DE_CASA',
}


print("\nRenomeando colunas do questionário...")
df2023_3 = df2023_2.rename(columns=mapa_renomeacao_2023)
print("Colunas renomeadas!")


print("\n--- DataFrame de 2023 TRATADO E PRONTO PARA ANÁLISE ---")
print(f"O DataFrame tratado tem {df2023_3.shape[0]} linhas e {df2023_3.shape[1]} colunas.")

display(df2023_3.head())

Selecionando as colunas especificadas...
Colunas selecionadas com sucesso!

Renomeando colunas do questionário...
Colunas renomeadas!

--- DataFrame de 2023 TRATADO E PRONTO PARA ANÁLISE ---
O DataFrame tratado tem 2037884 linhas e 30 colunas.

,ANO_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_LOCALIZACAO,Q_TRABALHO_FORA_DE_CASA,PROFICIENCIA_MT_SAEB,Q_COR_RACA,Q_ESCOLARIDADE_MAE,...,Q_MORA_COM_MAE,Q_MORA_COM_PAI,Q_BENS_GELADEIRA,Q_BENS_COMPUTADOR,Q_BENS_QUARTOS,Q_BENS_TV_CORES,Q_BENS_BANHEIRO,Q_BENS_CARRO,Q_TRABALHO_DOMESTICO,Q_LAZER
0,2023,1,11,6322170,2,1,D,218.734766,C,D,...,B,B,B,B,C,B,B,B,D,D
1,2023,1,11,6322170,2,1,.,186.094318,B,F,...,B,.,.,.,C,.,.,.,.,D
2,2023,1,11,6322170,2,1,A,242.608224,C,B,...,B,B,B,A,D,B,B,B,D,C
3,2023,1,11,6322170,2,1,D,227.650431,.,B,...,B,B,B,B,D,B,B,B,C,B
4,2023,1,11,6322170,2,1,A,266.778246,C,D,...,A,A,C,B,D,B,D,C,D,C

In [4]:
# --- HARMONIZAÇÃO E SOBRESCRITA DAS RESPOSTAS DE 2019 ---

# 1. Escolaridade
# CORREÇÃO: As chaves do dicionário agora são minúsculas ('a', 'b', 'c'...)
mapa_esc_2023_em_diante = {
    'A': 'A', #'Fundamental Incompleto',
    'B': 'A', #'Fundamental Incompleto',
    'C': 'B', #'Fundamental Completo',
    'D': 'C', #'Médio Completo',
    'E': 'D', #'Superior Completo',
    'F': 'E'  #'Não sei'
}

# CORREÇÃO: Atribua o resultado de volta para sobrescrever as colunas
df2023_3['Q_ESCOLARIDADE_MAE'] = df2023_3['Q_ESCOLARIDADE_MAE'].map(mapa_esc_2023_em_diante)
df2023_3['Q_ESCOLARIDADE_PAI'] = df2023_3['Q_ESCOLARIDADE_PAI'].map(mapa_esc_2023_em_diante)


# 2. Frequência dos Pais na Reunião
# CORREÇÃO: As chaves do dicionário agora são minúsculas
mapa_reuniao_2023 = {
    'A': 'C', # Nunca ou quase nunca -> C
    'B': 'B', # De vez em quando -> B
    'C': 'A'  # Sempre ou quase sempre -> A
}

# CORREÇÃO: Atribua o resultado de volta para sobrescrever a coluna
df2023_3['Q_PAIS_VAO_REUNIAO'] = df2023_3['Q_PAIS_VAO_REUNIAO'].map(mapa_reuniao_2023)


# 3. Incentivo dos Pais
# CORREÇÃO: As chaves do dicionário agora são minúsculas
mapa_frequencia_para_binario = {
    'A': 'B', # Nunca -> Não
    'B': 'A', # De vez em quando -> Sim
    'C': 'A'  # Sempre -> Sim
}

colunas_para_unificar = [
    'Q_PAIS_INCENTIVA_ESTUDAR',
    'Q_PAIS_INCENTIVA_DEVER',
    'Q_PAIS_INCENTIVA_IR_ESCOLA',
    'Q_PAIS_CONVERSA_SOBRE_ESCOLA'
]

for coluna in colunas_para_unificar:
    # CORREÇÃO: Atribua o resultado de volta para sobrescrever a coluna
    df2023_3[coluna] = df2023_3[coluna].map(mapa_frequencia_para_binario)

mapa_trabalho_fora = {
    'A': 'B', # Nunca -> Não
    'B': 'A', # De vez em quando -> Sim
    'C': 'A',  # Sempre -> Sim
    'D': 'A'
}
df2023_3['Q_TRABALHO_FORA_DE_CASA'] = df2023_3['Q_TRABALHO_FORA_DE_CASA'].map(mapa_trabalho_fora)

print("Todas as colunas de 2023 foram transformadas e sobrescritas com sucesso!")

Todas as colunas de 2023 foram transformadas e sobrescritas com sucesso!

In [5]:
import pandas as pd
import numpy as np

# --- PASSO 1: PADRONIZAR VALORES FALTANTES ---
valores_para_substituir = ['.', '*', np.nan]
print("Padronizando valores faltantes para '*' em todos os DataFrames...")
df2023_3 = df2023_3.replace(valores_para_substituir, '*')

nome_arquivo_final = 'SAEB_UNIFICADO_2023.csv'
print(f"\nExportando para '{nome_arquivo_final}'...")
df2023_3.to_csv(nome_arquivo_final, index=False, sep=';', encoding='utf-8-sig')
print("🎉 Processo concluído com sucesso!")

Padronizando valores faltantes para '*' em todos os DataFrames...

Exportando para 'SAEB_UNIFICADO_2023.csv'...
🎉 Processo concluído com sucesso!